config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  
  resources :orders, only: [:new, :create, :show, :edit, :update, :destroy] do
     resources :pizzas, only: [:new, :show, :create]
  end
  
 
  root      "home#index"

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  # Create by Rui Geng
  belongs_to :order
  before_save :format_toppings, :get_size_price, :get_toppings_price, :get_crust_price, :get_total_price
  after_save :update_order_subtotal
  
  default_scope -> { order(created_at: :desc) }

  validates :order_id, presence: true
  
  validates :pizza_type, presence: true, length: { maximum: 25 }
  
  validates :pizza_size, presence: true, length: { maximum: 25 }

  #validates :toppings, presence: true, length: { maximum: 254 }
  
  validates :crust, presence: true, length: { maximum: 254 }
  
  protected
    def format_toppings
      self.toppings.gsub!(/[\[\]\"]/, "") if attribute_present?("toppings")
    end
    
    def get_size_price
      if self.pizza_size == 'small'
        self.size_price = 5
      elsif self.pizza_size == 'medium'
        self.size_price = 10
      elsif self.pizza_size == 'large'
        self.size_price = 15
      elsif self.pizza_size == 'X-large'
        self.size_price = 20
      else
        self.size_price = 5
      end
    end
    
    def get_toppings_price
      topping_count = self.toppings.split(",").count
      if topping_count != 0
          self.toppings_price = (topping_count - 1) * 0.50
      end
    end
    
    def get_crust_price
      if self.crust == 'stuffed'
          self.crust_price = 2
      end
    end
    
    def get_total_price
      self.total_price = self.type_price + self.size_price + self.toppings_price + self.crust_price
    end
    
    def update_order_subtotal
      self.order.update_subtotal
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  # Create by Rui Geng
  before_action :set_order, only: [:create, :new]
  before_action :set_pizza, only: [:show]
  
  def new
    @pizza = Pizza.new
  end
  
  def show
  end

  def create
    respond_to do |format|
      @pizzas = @order.pizzas.build(pizza_params)
      if @pizzas.save
        @order = Order.find(@pizzas.order.id)
        @order.update_subtotal
        format.html { redirect_to new_order_pizza_path, notice: 'Pizza was successfully added to the Order.' }
      else
        format.html { redirect_to new_order_path, notice: 'Pizza was failed.' }
      end
    end
  end
  
  private
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end
  
    def set_order
      @order = Order.find(params[:order_id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Pleae Create an Order first!"
        redirect_to new_order_path
    end  
    
    def pizza_params
      params.require(:pizza).permit(:pizza_type, :pizza_size, :crust, toppings:[])
    end
end

app/helpers/pizzas_helper.rb
module PizzasHelper
  # Create by Rui Geng
  def checked(area)
    @pizza.toppings.nil? ? false : @pizza.toppings.match(area)
  end
end

app/views/pizzas/_form.html.erb
<div class = "row">
<%= form_for [@order, @pizza] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <h3>Your Shopping Cart <span class="label label-default"><%= @order.pizzas.count %></span> Pizzas</h3>
    <div class="row panel panel-primary">
      <div class="panel-heading">PIZZA</div>
        <div class="col-lg-6 col-md-6 col-sm-6">
          <%= image_tag "Pizza/Pizza1.jpg", :class => "img-responsive img-rounded" %>
          <%= f.radio_button :pizza_type, 'Original', :checked => true %>
          <%= f.label :pizza_type_original, "Original Pizza" %>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
          <%= image_tag "Pizza/Pizza2.jpg", :class => "img-responsive img-rounded" %>
          <%= f.radio_button :pizza_type, 'California'  %> 
          <%= f.label :pizza_type_california, "California Pizza" %>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
          <%= image_tag "Pizza/Pizza3.jpg", :class => "img-responsive img-rounded" %>
          <%= f.radio_button :pizza_type, 'Neapolitan'  %> 
          <%= f.label :pizza_type_neapolitan, "Neapolitan Pizza" %>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
          <%= image_tag "Pizza/Pizza3.jpg", :class => "img-responsive img-rounded" %>
          <%= f.radio_button :pizza_type, 'Poutine'  %> 
          <%= f.label :pizza_type_poutine, "Poutine Pizza" %>
        </div>
    </div>
    
  <div class="row panel panel-primary">
    <div class="panel-heading">SIZE</div>
     <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
      <%= image_tag "size/small.png", :class => "img-responsive img-rounded" %>
      <%= f.radio_button :pizza_size, "Small", :checked => true  %>
      <%= f.label :pizza_size_small, "Small" %>
     </div>

     <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
      <%= image_tag "size/medium.png", :class => "img-responsive img-rounded" %>
      <%= f.radio_button :pizza_size, "Medium"  %> 
      <%= f.label :pizza_size_medium, "Medium" %>
     </div>

     <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
      <%= image_tag "size/Large.png", :class => "img-responsive img-rounded" %>
      <%= f.radio_button :pizza_size, "Large"  %> 
      <%= f.label :pizza_size_large, "Large" %>
     </div>    

     <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
      <%= image_tag "size/xlarge.png", :class => "img-responsive img-rounded" %>
      <%= f.radio_button :pizza_size, "X-large"  %> 
      <%= f.label :pizza_size_xlarge, "X-large" %>
     </div>
    </div>
    
  <div class="row panel panel-primary">
    <div class="panel-heading">TOPPINGS</div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= image_tag "topping/onion.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_onion"><%= check_box_tag 'pizza[toppings][]', 'onion', checked('Onion'), id: 'toppings_onion' %>Onion</label>   
    
      <%= image_tag "topping/pepper.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_pepper"><%= check_box_tag 'pizza[toppings][]', 'pepper', checked('Pepper'), id: 'toppings_pepper' %>Green Pepper</label>

      <%= image_tag "topping/mushroom.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_mushroom"><%= check_box_tag 'pizza[toppings][]', 'mushroom', checked('Mushroom'), id: 'toppings_mushroom' %>Mushroom</label>
      
      <%= image_tag "topping/olives.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_olives"><%= check_box_tag 'pizza[toppings][]', 'olives', checked('Olives'), id: 'toppings_olives' %>Olives</label>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= image_tag "topping/pineapple.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_pineapple"><%= check_box_tag 'pizza[toppings][]', 'pineapple', checked('Pineapple'), id: 'toppings_pineapple' %>Pineapple</label>
      
      <%= image_tag "topping/asparagus.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_asparagus"><%= check_box_tag 'pizza[toppings][]', 'asparagus', checked('Asparagus'), id: 'toppings_asparagus' %>Asparagus</label>
      
      <%= image_tag "topping/pepperoni.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_pepperoni"><%= check_box_tag 'pizza[toppings][]', 'pepperoni', checked('Pepperoni'), id: 'toppings_pepperoni' %>Pepperoni</label>
      
      <%= image_tag "topping/bacon.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_bacon"><%= check_box_tag 'pizza[toppings][]', 'bacon', checked('Bacon'), id: 'toppings_bacon' %>Bacon</label>
    </div>   
  
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <%= image_tag "topping/ham.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_ham"><%= check_box_tag 'pizza[toppings][]', 'ham', checked('Ham'), id: 'toppings_ham' %>Ham</label>

      <%= image_tag "topping/beef.png", :class => "img-responsive img-rounded" %>      
      <label id="toppings_beef"><%= check_box_tag 'pizza[toppings][]', 'beef', checked('Beef'), id: 'toppings_beef' %>Beef</label>

      <%= image_tag "topping/sausage.png", :class => "img-responsive img-rounded" %>      
      <label id="toppings_sausage"><%= check_box_tag 'pizza[toppings][]', 'sausage', checked('Sausage'), id: 'toppings_sausage' %>Sausage</label>

      <%= image_tag "topping/Chicken.png", :class => "img-responsive img-rounded" %>
      <label id="toppings_chicken"><%= check_box_tag 'pizza[toppings][]', 'chicken', checked('Chicken'), id: 'toppings_chicken' %>Buffalo Chicken</label>
    </div>
  </div>

  <div class="row panel panel-primary">
    <div class="panel-heading">CRUST</div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
      <%= image_tag "type/None.jpeg", :class => "img-responsive img-rounded" %>
      <%= f.radio_button :crust, :none, :checked => true %>
      <%= f.label :crust_none, "Normal" %>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
      <%= image_tag "type/Crust.jpeg", :class => "img-responsive img-rounded" %>
      <%= f.radio_button :crust, :stuffed %>
      <%= f.label :crust_stuffed, "Stuffed Crust" %>
    </div>
  </div>
    
  <div class="row">
    <%= f.submit "Add Current Pizza to Order", class: "btn btn-primary" %>
  </div>
<% end %>

<% if @order.pizzas.count > 0 %>
  <div class="row">
    <%= button_to "Go To Pay Order", order_path(@order.id), :class => "btn btn-success", :method=> :get %>
  </div>
<% end %>
</div>

app/views/pizzas/_pizza.html.erb
<li id="order-<%= pizza.id %>">
  <span class="content">
    <strong>Pizza Type: </strong><%= pizza.pizza_type %>
  </span>
  <span class="content">
    <strong>Pizza Size: </strong><%= pizza.pizza_size %>
  </span>
  <span class="content">
    <strong>Pizza Toppings: </strong>:<%= pizza.toppings %>
  </span>
  <span class="content">
    <strong>Pizza Crust: </strong><%= pizza.crust %>
  </span>
  <span class="content">
    <strong>Pizza Price: </strong><%= pizza.total_price %>
  </span>
  <span class="timestamp">
    Created <%= time_ago_in_words(pizza.created_at) %> ago.
  </span>
</li>

app/views/pizzas/new.html.erb
<h1>Make a New Pizza</h1>

<%= render 'form' %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pizza Type:</strong>
  <%= @pizza.pizza_type %>
</p>

<p>
  <strong>Pizza Size:</strong>
  <%= @pizza.pizza_size %>
</p>