config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  
  resources :orders, only: [:new, :create, :show, :edit, :update, :destroy] do
     resources :pizzas, only: [:new, :show, :create]
  end
  
 
  root      "home#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  # Create by Rui Geng
  belongs_to :user
  has_many :pizzas, dependent: :destroy
  before_save :get_taxrate

  default_scope -> { order(created_at: :desc) }
  
  VALID_PHONE_REGEX = /\d{3}-?\d{3}-?\d{4}/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_POSTALCODE_REGEX = /[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ] ?[0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]/
  validates :user_id, presence: true

  validates :first_name, presence: true, length: { maximum: 25 }
  
  validates :last_name, presence: true, length: { maximum: 25 }
  
  validates :phone_number, presence: true, 
            format: { with: VALID_PHONE_REGEX, message: "Please Enter a Valid Phone Number" }
            
  validates :email, presence: true, length: { maximum: 254 }, 
            format: { with: VALID_EMAIL_REGEX , message: "Please Enter a Valid Eemail Address" }
            
  validates :address_line1, presence: true, length: { maximum: 50 }
  
  validates :address_line2, presence: true, length: { maximum: 50 }
  
  validates :province, presence: true, length: { maximum: 25 }
  
  validates :city, presence: true, length: { maximum: 25 }
  
  validates :postal_code, presence: true, 
            format: { with: VALID_POSTALCODE_REGEX, message: "Please Enter a Valid Postal Code" }
  
  
  def update_subtotal
    self.update_column(:subtotal, self.pizzas.sum(:total_price))
    self.update_column(:total, self.subtotal * self.tax )
  end
  
  protected          
    def get_taxrate
      if self.province == 'ontario'
        self.tax = 1.13
      elsif self.province == 'quebec'
        self.tax = 1.11
      elsif self.province == 'manitoba'
        self.tax = 1.10
      elsif self.province == 'saskatchewan'
        self.tax = 1.15
      else
        self.tax = 1.13
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Create by Rui Geng
  before_action :is_admin, only: [:destroy, :edit, :update]
  before_action :set_order, only: [:show, :destroy, :edit, :update]
  before_action :set_pizza, only: [:show, :destroy]

  def new
     @order = Order.new
  end
  
  def show
     @pizzas = @order.pizzas.paginate(page: params[:page], :per_page => 5)
  end
  
  def create
    @order = current_user.orders.build(order_params)
    if @order.save
      flash[:notice] = "Order was successfully generated."
      redirect_to new_order_pizza_path(:order_id => @order.id)
    else
      flash[:alert] = "Order was failed!"
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to user_path(current_user.id), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end
    
    def set_pizza
      @pizzas = Pizza.where(order_id: params[:id])
    end
    
    def is_admin
      if !current_user.admin
        redirect_to root_url
      end
    end
  
    def order_params
      params.require(:order).permit(:first_name, :last_name, :phone_number, 
                                    :email, :address_line1, :address_line2,
                                    :province, :city, :postal_code, :is_dilivery, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_edit_form.html.erb
<div class="row">
  <%= form_for(@order) do |f| %>
   
    <%= render 'shared/error_messages', object: f.object %>
    
    <fieldset class="form-group">
      <legend>Delivery Contact</legend>
      <div class="form-group row">
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :first_name %><br>
           <%= f.text_field :first_name, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :last_name %><br>
           <%= f.text_field :last_name, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :phone_number %><br>
           <%= f.telephone_field :phone_number, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :email %><br>
           <%= f.email_field :email, class: "form-control" %>
         </div>
    </fieldset>
    
    <fieldset class="form-group">
      <legend>Delivery Address</legend>
      <div class="form-group row">
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :address_line1 %><br>
           <%= f.text_field :address_line1, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :address_line2 %><br>
           <%= f.text_field :address_line2, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-4 col-md-4 col-sm-4">
           <%= f.label :province %><br>
           <%= f.select( :province, options_for_select([['Ontario', "ontario"], ['Quebec',  "quebec"],
                                     ['Manitoba',  "manitoba"], ['Saskatchewan',  "saskatchewan"]]), {}, {class: "form-control"}) %>
         </div>
         
         <div class="form-group col-lg-4 col-md-4 col-sm-4">
           <%= f.label :city %><br>
           <%= f.text_field :city, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-4 col-md-4 col-sm-4">
           <%= f.label :postal_code %><br>
           <%= f.text_field :postal_code, class: "form-control" %>
         </div>
    </fieldset>

    <% if current_user.admin? %>
      <fieldset class="form-group">      
        <div class="field">
          <%= f.check_box :is_dilivery%>
          <%= f.label :complete %>
        </div>
      </fieldset>
    <% end %>
  
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/orders/_form.html.erb
<div class="row">
  <%= form_for(@order) do |f| %>
   
    <%= render 'shared/error_messages', object: f.object %>
    
    <fieldset class="form-group">
      <legend>Delivery Contact</legend>
      <div class="form-group row">
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :first_name %><br>
           <%= f.text_field :first_name, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :last_name %><br>
           <%= f.text_field :last_name, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :phone_number %><br>
           <%= f.telephone_field :phone_number, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :email %><br>
           <%= f.email_field :email, class: "form-control" %>
         </div>
    </fieldset>
    
    <fieldset class="form-group">
      <legend>Delivery Address</legend>
      <div class="form-group row">
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :address_line1 %><br>
           <%= f.text_field :address_line1, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-6 col-md-6 col-sm-6">
           <%= f.label :address_line2 %><br>
           <%= f.text_field :address_line2, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-4 col-md-4 col-sm-4">
           <%= f.label :province %><br>
           <%= f.select( :province, options_for_select([['Ontario', "ontario"], ['Quebec',  "quebec"],
                                     ['Manitoba',  "manitoba"], ['Saskatchewan',  "saskatchewan"]]), {}, {class: "form-control"}) %>
         </div>
         
         <div class="form-group col-lg-4 col-md-4 col-sm-4">
           <%= f.label :city %><br>
           <%= f.text_field :city, class: "form-control" %>
         </div>
         
         <div class="form-group col-lg-4 col-md-4 col-sm-4">
           <%= f.label :postal_code %><br>
           <%= f.text_field :postal_code, class: "form-control" %>
         </div>
    </fieldset>

    <div class="actions">
      <%= f.submit "Continue to Order Pizza", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/orders/_order.html.erb
<li id="order-<%= order.id %>">
  <span class="content">
    <strong>Order ID: </strong><%= order.id %>
  </span>
  <span class="content">
    <strong>Customer First Name: </strong><%= order.first_name %>
  </span>
  <span class="content">
    <strong>Customer Last Name: </strong><%= order.last_name %>
  </span>
  <span class="content">
    <strong>Customer Phone Number: </strong><%= order.phone_number %>
  </span>
  <% if order.is_dilivery? %>
     <p><h3><span class="label label-success">This Order Was Completed</span></h3></p>
  <% end %>

  <span class="timestamp">
    Created <%= time_ago_in_words(order.created_at) %> ago.
  </span>
  <span class="order"><%= link_to 'Show Order', order %></span> |

  <% if current_user.admin? %>
    <span class="order"><%= link_to 'Edit Order', edit_order_path(order) %></span> |
    <span class="order"><%= link_to 'Destroy Order', order, method: :delete, data: { confirm: 'Are you sure?' } %></span>
  <% end %>
</li>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'edit_form' %>


<%= link_to 'Back', user_path(current_user) %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/orders/show.html.erb
<div class="row">
 <h1>The Order Information</h1>
 
 <div class="container">
   <div class="row">
    <div class="col-md-6 col-md-offset-3">
     <% if @order.pizzas.any? %>
       <h3>Pizza (<%= @order.pizzas.count %>)</h3>
       <ol class="orders">
       <%= render @pizzas %>
       </ol>
       <%= will_paginate @pizzas %>
     <% end %>
    </div>
   </div>
 </div>
 
 <div class="container">
  <div class="row">
   <div class="col-md-6 col-md-offset-3">
   <h3>Delivery Information</h3>
    <address>
     <strong>First Name: </strong><%= @order.first_name %><br>
     <strong>Last Name: </strong><%= @order.last_name %><br>
     <strong>Phone Number: </strong><%= @order.phone_number %><br>
     <strong>Email address: </strong><%= @order.email %><br>
     <strong>Address Line 1: </strong><%= @order.address_line1 %><br>
     <strong>Address Line 2: </strong><%= @order.address_line2 %><br>
     <strong>Province: </strong><%= @order.province %><br>
     <strong>City: </strong><%= @order.city %><br>
     <strong>Postal Code: </strong><%= @order.postal_code %><br>
    </address>
    </div>
  </div>
 </div>
 <div class="container">
   <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h3>Pirce Information</h3>
     <strong>Subtotal: </strong>$<%= @order.subtotal %><br>
     <strong>Tax: </strong><%= @order.tax %><br>
     <strong>Total: </strong>$<%= @order.total %><br>
     </div>
   </div>
 </div>
 <div class="container">
   <div class="row">
    <div class="col-md-6 col-md-offset-3">
     <span><%= link_to "Back", :back %></span> | 
     <span><%= link_to "Finish", root_url %></span>
    </div>
   </div>
 </div>
</div>