config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  
  resources :orders, only: [:new, :create, :show, :edit, :update, :destroy] do
     resources :pizzas, only: [:new, :show, :create]
  end
  
 
  root      "home#index"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Conestoga Pizzeria Application by Rui Geng
  </small>
  <nav>
    <ul>
      <li>Student Name: Rui Geng</li>
      <li>Student Number: 7128218</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Conestoga Pizzeria", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "MENU", '#' %></li>
        <li><%= link_to "ORDER", new_order_path %></li>
        <li><%= link_to "CONTACT", '#' %></li>
      </ul> 
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%if current_user.admin %>
            <li><%= link_to "Manage Users", users_path %></li>
          <% end %>
          <li><%= link_to "Manage Order", current_user %></li>
          <li><%= link_to "Update Account", edit_user_registration_path(@user) %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else  %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Conestoga Pizzeria</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    
    <% if notice -%>
      <p class="alert alert-success"><%= notice %></p>
    <% end -%>
    
    <% if alert -%>
      <p class="alert alert-warning"><%= alert %></p>
    <% end -%>
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>